In [29]:
import tensorflow as tf

# 2.1.1 Getting Started

tensor는 숫자로 이루어진 array(배열)로 나타낸다. axis가 1개인 tensor를 vector라고 하고, axis가 2개인 tensor를 matrix라고 한다.
축이 $k>2$ 이면, $k^{th}$ order tensor라고 한다.

tensorflow는 새로운 tensor를 생성하기 위한 다양한 기능을 제공한다. 예를 들어 arange(n)을 호출하면 0(포함)에서 시작하여 n(포함되지 않음)에서 끝나는 균일한 간격의 값(interval size=1)으로 구성된 vector를 생성할 수 있다. tensor의 각 value들을 element라고 부르며 tensor x는 12개의 elements을 가지고 있다고 말할 수 있다. size 함수를 이용하여 elements의 총 개수를 확인할 수 있다.

In [30]:
x = tf.range(12, dtype=tf.float32)
x

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

In [31]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

shape을 이용해서 tensor의 shape(각 axis에 따른 길이)를 확인할 수 있으며, reshape를 이용해서 tensor의 shape을 변경할 수 있다. reshape 시 elements은 유지된다. 

tensor의 size가 $n$일 때, tensor을 $(h, w)$로 reshape하게 되면, $w = n/h$가 성립한다.

In [32]:
x.shape

TensorShape([12])

In [33]:
X = tf.reshape(x, (3, 4))
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

reshape 시 $(h ,w)$ 중 한 component가 정해졌을 때, 다른 component를 -1로 입력하면, $w=n/h$가 성립되도록 자동으로 설정된다.

In [34]:
X = tf.reshape(x, (3, -1))
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [35]:
X = tf.reshape(x, (-1, 4))
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

zeros 함수는 elements가 모두 0으로 이루어진 tensor를 생성한다.

ones 함수는 elements가 모두 1로 이루어진 tensor를 생성한다.

randn 함수는 평균이 0이고 표준편차가 1인 가우시안 분포를 따르는 elements가 random으로 할당되는 tensor를 생성한다.

In [36]:
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [37]:
tf.ones((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [38]:
tf.random.normal(shape=[3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.5547738 ,  0.80187196, -2.027972  , -0.150351  ],
       [-1.7571307 , -0.5705302 , -1.2692368 ,  0.32208198],
       [ 0.8157289 , -0.6593362 ,  0.4000413 ,  0.40984836]],
      dtype=float32)>

list를 여러개 붙여서 tensor를 형성할 수도 있다.

In [39]:
tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

# 2.1.2 Indexing and Slicing

python list와 마찬가지로 index가 0에서 시작한다. 음수 indexing도 가능하며, -1은 list의 끝을 의미한다. 

In [40]:
X[-1], X[1:3]

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>)

tensor는 immutable하다. variable은 mutable container이며 변수의 assign을 지원한다.

In [41]:
X_var = tf.Variable(X)
X_var[1, 2].assign(9)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [42]:
X_var = tf.Variable(X)
X_var[:2, :].assign(tf.ones(X_var[:2,:].shape, dtype=tf.float32) * 12)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

# 2.1.3 Operations

exp(x)는 $e^x$ 함수에 해당하는 operator이다.

In [43]:
tf.exp(x)

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([1.0000000e+00, 2.7182817e+00, 7.3890562e+00, 2.0085537e+01,
       5.4598148e+01, 1.4841316e+02, 4.0342880e+02, 1.0966332e+03,
       2.9809580e+03, 8.1030840e+03, 2.2026467e+04, 5.9874141e+04],
      dtype=float32)>

덧셈, 뺄셈, 곱셈, 나눗셈, 거듭제곱이 가능하다.

In [44]:
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>)

tensor를 concatenate 할 수 있다. dim=0은 row, dim=1은 column을 기준으로 tensor를 합친다.
(3,4) tensor 2개를 axis=0으로 concatenate하면 (3+3, 4)의 shape으로, axis=1로 concatenate하면 (3, 4+4)의 shape으로 만들어진다.


In [45]:
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
tf.concat([X, Y], axis=0), tf.concat([X, Y], axis=1)

(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>)

==는 각 tensor의 elements를 비교할 수 있는 비교연산자 이다.

In [46]:
X == Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

reduce_sum을 이용하면 tensor의 모든 elements의 합을 element로 갖는 tensor가 생성된다.

In [47]:
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

# 2.1.4 Broadcasting

In [48]:
a = tf.reshape(tf.range(3), (3, 1))
b = tf.reshape(tf.range(2), (1, 2))
a, b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [49]:
a + b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

# 2.1.5 Saving Memory

In [50]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [51]:
Z = tf.Variable(tf.zeros_like(Y))
print('id(Z):', id(Z))
Z.assign(X + Y)
print('id(Z):', id(Z))

id(Z): 1665242263944
id(Z): 1665242263944


In [52]:
@tf.function
def computation(X, Y):
    Z = tf.zeros_like(Y)  # This unused value will be pruned out
    A = X + Y  # Allocations will be reused when no longer needed
    B = A + Y
    C = B + Y
    return C + Y

computation(X, Y)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: No module named 'tensorflow_core.estimator'
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: No module named 'tensorflow_core.estimator'


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 8.,  9., 26., 27.],
       [24., 33., 42., 51.],
       [56., 57., 58., 59.]], dtype=float32)>

# 2.1.6 Conversion to Other Python Objects

from_numpy를 이용해 numpy type을 tensor type으로 바꿀 수 있다.

In [53]:
A = X.numpy()
B = tf.constant(A)
type(A), type(B)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)

In [54]:
a = tf.constant([3.5]).numpy()
a, a.item(), float(a), int(a)

(array([3.5], dtype=float32), 3.5, 3.5, 3)